[package]
name = "tproxy-config"
version = "6.0.0"
edition = "2021"
description = "Transparent proxy configuration"
license = "MIT"
authors = ["@ssrlive"]
repository = "https://github.com/ssrlive/tproxy-config"
keywords = ["tun", "network", "tunnel", "transparent", "proxy"]
readme = "readme.md"

[features]
default = []
log = ["dep:log"]

[dependencies]
cidr = { version = "0.2", features = ["serde"] }
log = { version = "0.4", optional = true }
regex = "1.10"

[target.'cfg(target_os = "macos")'.dependencies]
resolv-conf = "0.7"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.29", features = ["fs", "mount", "process"] }
tempfile = "3.10"
